name: templai
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.5 <3.0.0'

dependencies:
  dart_openai: ^1.9.1
  flutter:
    sdk: flutter
  provider: ^6.0.5
  shared_preferences: ^2.0.20
  url_launcher: ^6.1.10
  webview_flutter: ^4.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
